name: hello world

on:
 push: 
  branches: 
   - main

jobs:
  hello_world_job:
   runs-on: ububtu-20.04
   steps: 
    - name: Say hello
      run: |
       echo "Hello World!"
    - name: Now it is
      run: |
       echo "date"
    - name: Directory content
      run: |
       echo: "ls -l"
 
 
