name: date and dir

on:
 push: 
  branches: 
   - main

jobs:
  hello_world_job:
   runs-on: Ubuntu-20.04
   steps: 
    - name: Say hello
      run: |
       echo "Hello World!"
    - name: Now it is
      run: date
       echo "The date is:"
    - name: Directory content
      run: ls -l 
 
 
