name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Run Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Send Discord success notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"✅ Test Succeeded!\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord failure notification
        if: failure()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "❌ Build failed",
                "description": "Commit [7418d335...](https://github.com/your-repo/commit/7418d3352ca4e6b8adad9c93f14cb9fe75652b99) by **your-username** broke the build 😞",
                "color": 16711680,
                "footer": {
                  "text": "Severity: Error • $(date)"
                }
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}


      - name: Send Discord cancelled notification
        if: cancelled()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"⚠️ Test Cancelled!\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

  deploy_to_render:
    name: Deploy to Render
    needs: simple_deployment_pipeline
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}

  health_check:
    name: Check the deployed service URL
    needs: deploy_to_render
    runs-on: ubuntu-latest
    steps:
      - name: Check service health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-i3nu.onrender.com
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false

  notify_success:
    name: Notify Deployment Success
    needs: health_check
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification to Discord
        run: |
         curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "🚀 A new version of Pokedex deployed",
                "description": "to [https://full-stack-open-pokedex-i3nu.onrender.com](https://full-stack-open-pokedex-i3nu.onrender.com) by **your-username**",
                "color": 65280,
                "footer": {
                  "text": "Severity: Informational • $(date)"
                }
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}

